# fly.toml app configuration file generated for openapo on 2024-10-21T22:13:03-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'openapo'
primary_region = 'arn'

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']
[http_service.concurrency]
type = "requests"
soft_limit = 80
hard_limit = 100

[[vm]]
size = "shared-cpu-1x"
